'use strict';
/*
 * Pre-renders elephantdoorstudios.com into plain HTML for GitHub Pages.
 *
 *   npm run build     write every generated file (the ones that begin with the "Generated by" comment)
 *   npm run check     exit 1 and list the files that are out of date (used by the GitHub Action)
 *
 * Inputs:  site.json (facts and IDs), src/pages/*.html (page templates with a JSON front matter block),
 *          src/partials/*.html (shared pieces), blog/posts.json + blog/posts/<slug>.md (the posts),
 *          assets/screenshots, assets/gifs, assets/logos (listed into the galleries).
 * Outputs: index.html, 404.html, warlock/index.html, press/index.html, blog/index.html,
 *          blog/<slug>/index.html for every post, feed.xml (RSS 2.0), sitemap.xml.
 *
 * The markdown is rendered with the same marked 15 the old client-side pages loaded from the CDN, and the
 * YouTube embed rule is the one those pages used, so the posts look as they did before.
 */
const fs = require('fs');
const path = require('path');
const { marked } = require('marked');
const Mustache = require('mustache');

const ROOT = path.resolve(__dirname, '..');
const CHECK = process.argv.includes('--check');
const GENERATED = '<!-- Generated by tools/build.js. Edit src/ (pages, partials), site.json or blog/posts/ and run `npm run build`; do not edit this file. -->\n';
const IMAGE_EXT = /\.(png|jpe?g|gif|webp)$/i;

// Mustache escapes "/" and "=" too by default, which makes URLs unreadable in the source; plain HTML escaping is enough.
Mustache.escape = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const exists = (rel) => fs.existsSync(path.join(ROOT, rel));
const xml = (s) => String(s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));

function loadSite() {
	const site = JSON.parse(read('site.json'));
	const game = site.game;
	game.steam_url = game.steam_app_id
		? `https://store.steampowered.com/app/${game.steam_app_id}/` + (game.steam_utm ? `?${game.steam_utm}` : '')
		: '';
	site.twitter_handle = (site.twitter || '').replace(/^@/, '');
	site.absolute = (p) => (/^https?:\/\//.test(p) ? p : site.url + p);
	return site;
}

function analyticsTag(a) {
	if (!a || !a.code) return '<!-- analytics: set analytics.code in site.json (GoatCounter site code or Plausible domain) to enable -->';
	if (a.provider === 'goatcounter') {
		return `<script data-goatcounter="https://${a.code}.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>`;
	}
	if (a.provider === 'plausible') {
		return `<script defer data-domain="${a.code}" src="https://plausible.io/js/script.js"></script>`;
	}
	throw new Error(`site.json: unknown analytics.provider "${a.provider}" (goatcounter or plausible)`);
}

function loadPartials() {
	const dir = path.join(ROOT, 'src', 'partials');
	const partials = {};
	for (const f of fs.readdirSync(dir)) {
		if (f.endsWith('.html')) partials[f.replace(/\.html$/, '')] = fs.readFileSync(path.join(dir, f), 'utf8');
	}
	return partials;
}

function parseFrontMatter(text, name) {
	const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(text);
	if (!m) throw new Error(`${name}: missing the JSON front matter block`);
	let meta;
	try {
		meta = JSON.parse(m[1]);
	} catch (e) {
		throw new Error(`${name}: front matter is not valid JSON (${e.message})`);
	}
	return { meta, body: text.slice(m[0].length) };
}

// Files in an asset folder, in name order, as gallery entries. "01-goblin-den.png" gets the alt text "goblin den".
function listFiles(dir, filter) {
	if (!exists(dir)) return [];
	return fs.readdirSync(path.join(ROOT, dir))
		.filter((f) => !f.startsWith('.') && filter.test(f))
		.sort()
		.map((f) => ({
			src: `/${dir}/${f}`,
			name: f,
			alt: f.replace(/\.[^.]+$/, '').replace(/^\d+[-_ ]*/, '').replace(/[-_]+/g, ' ').trim() || f,
		}));
}

// The rule the old client-side post pages applied to marked's output: a paragraph holding only a YouTube link
// becomes a responsive embed.
function embedYouTube(html) {
	return html.replace(
		/<p><a href="https?:\/\/(?:www\.)?(?:youtube\.com\/watch\?(?:[^"]*&)?v=|youtu\.be\/)([\w-]+)[^"]*">[^<]*<\/a><\/p>/g,
		(_, id) => `<div class="yt-embed"><iframe src="https://www.youtube.com/embed/${id}" allowfullscreen></iframe></div>`,
	);
}

// Root-relative src/href attributes become absolute, for the feed (readers and mail clients have no base URL).
const absolutize = (html, base) => html.replace(/\b(src|href)="\/(?!\/)/g, `$1="${base}/`);

function firstParagraphText(html) {
	const m = /<p>([\s\S]*?)<\/p>/.exec(html);
	if (!m) return '';
	const text = m[1].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
	return text.length > 160 ? text.slice(0, 157).replace(/\s+\S*$/, '') + '...' : text;
}

function loadPosts(site) {
	const list = JSON.parse(read('blog/posts.json'));
	return list.map((p) => {
		const slug = String(p.slug);
		const source = `blog/posts/${slug}.md`;
		if (!exists(source)) throw new Error(`blog/posts.json lists slug ${slug} but ${source} does not exist`);
		if (!/^\d{4}-\d{2}-\d{2}$/.test(p.date || '')) throw new Error(`blog/posts.json: post ${slug} needs a date like 2026-03-31`);
		const html = marked.parse(read(source));
		const firstImage = /<img[^>]+src="([^"]+)"/.exec(html);
		return {
			slug,
			title: p.title,
			date: p.date,
			summary: p.summary || '',
			url: `${site.url}/blog/${slug}/`,
			html: embedYouTube(html),
			feed_html: absolutize(html, site.url),
			image: site.absolute(firstImage ? firstImage[1] : site.default_image),
			description: p.summary || firstParagraphText(html),
		};
	});
}

function rssFeed(site, posts, description) {
	const newest = posts.reduce((a, b) => (a.date > b.date ? a : b));
	const rfc822 = (date) => new Date(`${date}T00:00:00Z`).toUTCString();
	const items = posts.slice().reverse().map((p) => `    <item>
      <title>${xml(p.title)}</title>
      <link>${p.url}</link>
      <guid isPermaLink="true">${p.url}</guid>
      <pubDate>${rfc822(p.date)}</pubDate>
      <description>${xml(p.description)}</description>
      <content:encoded><![CDATA[${p.feed_html.replace(/\]\]>/g, ']]]]><![CDATA[>')}]]></content:encoded>
    </item>`).join('\n');
	return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>${xml(site.feed_title)}</title>
    <link>${site.url}/blog/</link>
    <atom:link href="${site.url}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>${xml(description || site.feed_title)}</description>
    <language>en</language>
    <lastBuildDate>${rfc822(newest.date)}</lastBuildDate>
${items}
  </channel>
</rss>
`;
}

function sitemap(site, pages, posts) {
	const entries = pages.map((url) => `  <url><loc>${url}</loc></url>`)
		.concat(posts.map((p) => `  <url><loc>${p.url}</loc><lastmod>${p.date}</lastmod></url>`));
	return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>
`;
}

function build() {
	const site = loadSite();
	const partials = loadPartials();
	const posts = loadPosts(site);
	const outputs = new Map();
	const emit = (rel, content) => outputs.set(rel.replace(/\\/g, '/'), content);

	const shared = {
		site,
		game: site.game,
		analytics: analyticsTag(site.analytics),
		screenshots: listFiles('assets/screenshots', IMAGE_EXT),
		gifs: listFiles('assets/gifs', /\.gif$/i),
		logos: listFiles('assets/logos', /\.(png|jpe?g|gif|webp|svg|ico)$/i),
	};
	const render = (template, page, extra) => GENERATED + Mustache.render(template, { ...shared, ...extra, page }, partials);
	const urlFor = (out) => `${site.url}/${out.replace(/(^|\/)index\.html$/, '$1')}`;

	// Static pages from src/pages (post.html is the per-post template and has out: null).
	const pagesDir = path.join(ROOT, 'src', 'pages');
	const sitemapUrls = [];
	let blogDescription = '';
	const postTemplate = parseFrontMatter(read('src/pages/post.html'), 'src/pages/post.html');
	// index.html first so the sitemap leads with the home page; the rest in name order.
	const pageFiles = fs.readdirSync(pagesDir).sort((a, b) => (a === 'index.html' ? -1 : b === 'index.html' ? 1 : a.localeCompare(b)));
	for (const f of pageFiles) {
		if (!f.endsWith('.html') || f === 'post.html') continue;
		const { meta, body } = parseFrontMatter(fs.readFileSync(path.join(pagesDir, f), 'utf8'), `src/pages/${f}`);
		if (!meta.out) continue;
		const page = {
			...meta,
			url: urlFor(meta.out),
			image: site.absolute(site.default_image),
			og_type: meta.og_type || 'website',
			description: meta.description || '',
		};
		if (meta.out === 'blog/index.html') blogDescription = page.description;
		if (!meta.no_sitemap) sitemapUrls.push(page.url);
		emit(meta.out, render(body, page, { posts: posts.slice().reverse() }));
	}

	// One page per post.
	for (const post of posts) {
		const page = {
			...postTemplate.meta,
			title: `${post.title} - ${site.name}`,
			description: post.description,
			url: post.url,
			image: post.image,
			published: post.date,
		};
		emit(`blog/${post.slug}/index.html`, render(postTemplate.body, page, { post }));
	}

	emit('feed.xml', rssFeed(site, posts, blogDescription));
	emit('sitemap.xml', sitemap(site, sitemapUrls, posts));
	return outputs;
}

function main() {
	const outputs = build();
	const normalise = (s) => s.replace(/\r\n/g, '\n');
	const stale = [];
	for (const [rel, content] of outputs) {
		const abs = path.join(ROOT, rel);
		const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
		if (current !== null && normalise(current) === normalise(content)) continue;
		if (CHECK) {
			stale.push(rel);
		} else {
			fs.mkdirSync(path.dirname(abs), { recursive: true });
			fs.writeFileSync(abs, content);
			console.log(`wrote ${rel}`);
		}
	}
	if (CHECK) {
		if (stale.length) {
			console.error(`Generated files are out of date; run \`npm run build\` and commit:\n  ${stale.join('\n  ')}`);
			process.exit(1);
		}
		console.log(`All ${outputs.size} generated files are up to date.`);
	} else {
		console.log(`${outputs.size} generated files checked.`);
	}
}

main();
